# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, csv: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param id: The id of this Body.  # noqa: E501
        :type id: int
        :param csv: The csv of this Body.  # noqa: E501
        :type csv: str
        """
        self.swagger_types = {
            'id': int,
            'csv': str
        }

        self.attribute_map = {
            'id': 'id',
            'csv': 'csv'
        }
        self._id = id
        self._csv = csv

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Body.


        :return: The id of this Body.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Body.


        :param id: The id of this Body.
        :type id: int
        """

        self._id = id

    @property
    def csv(self) -> str:
        """Gets the csv of this Body.


        :return: The csv of this Body.
        :rtype: str
        """
        return self._csv

    @csv.setter
    def csv(self, csv: str):
        """Sets the csv of this Body.


        :param csv: The csv of this Body.
        :type csv: str
        """

        self._csv = csv
